export const AUTH_LOGIN_REQUEST = 'LOGIN_REQUEST'
export const AUTH_LOGIN_FAILURE = 'LOGIN_FAILURE'
export const AUTH_LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const AUTH_LOGOUT = 'LOGOUT'
export const AUTH_SET_PROFILE = 'SET_PROFILE'


export const ERROR_ADD_NEW = 'ADD_NEW'
export const ERROR_CLEAR_ALL = 'CLEAR_ALL'

export const SERVICES_GET_ALL = 'GET_ALL'
export const SERVICES_ADD_NEW = 'ADD_NEW'

export const DEVICE_GET_ALL = 'GET_ALL'
export const DEVICE_ADD_NEW = 'ADD_NEW'
export const DEVICE_SET_PAGINATION = 'SET_PAGINATION'
export const DEVICE_PREV_PAGE = 'PREV_PAGE'
export const DEVICE_NEXT_PAGE = 'NEXT_PAGE'
export const DEVICE_ADD_FILTER = 'ADD_FILTER'
export const DEVICE_REMOVE_FILTER = 'REMOVE_FILTER'

export const MODIFICATION_GET_ALL = 'GET_ALL'
export const CARRIER_GET_ALL = 'GET_ALL'
