export const AUTH_LOGIN_REQUEST = 'LOGIN_REQUEST'
export const AUTH_LOGIN_FAILURE = 'LOGIN_FAILURE'
export const AUTH_LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const AUTH_LOGOUT = 'LOGOUT'
export const AUTH_SET_PROFILE = 'SET_PROFILE'

export const SERVICE_GET_ALL = 'GET_ALL'
export const SERVICE_ADD_NEW = 'ADD_NEW'