export const AUTH_LOGIN_REQUEST = 'LOGIN_REQUEST'
export const AUTH_LOGIN_FAILURE = 'LOGIN_FAILURE'
export const AUTH_LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const AUTH_LOGOUT = 'LOGOUT'
export const AUTH_SET_PROFILE = 'SET_PROFILE'
export const AUTH_REGISTER_USER ='REGISTER_USER'
export const AUTH_REGISTER_FAILURE ='REGISTER_FAILURE'
export const AUTH_PASSWORD_RECOVERY ='RECOVERY_VARIATIONS'


export const ERROR_ADD_NEW = 'ADD_NEW'
export const ERROR_CLEAR_ALL = 'CLEAR_ALL'

export const PRESET_GET_ALL = 'GET_ALL'
export const PRESETS_GET_PRESET = 'GET_ONE'
export const PRESET_PREPARE_VARIATIONS = 'PREPARE_VARIATIONS'
export const PRESET_ADD_NEW = 'ADD_NEW_PRESET'
export const PRESET_UPDATE = 'UPDATE_PRESET'
export const PRESET_NEXT_PAGE = 'NEXT_PAGE'
export const PRESET_PREV_PAGE = 'PREV_PAGE'



export const SERVICES_GET_ALL = 'GET_ALL'
export const SERVICES_GET_SERVICE = 'GET_ONE'
export const SERVICE_ADD_NEW = 'ADD_NEW_SERVICE'
export const SERVICE_UPDATE  =  'UPDATE_SERVICE'
export const SERVICE_PREPARE_ITEMS ='PREPARE_ITEMS'
export const SERVICE_ADDONS ='SERVICE_ADDONS'
export const SERVICE_PREV_PAGE = 'PREV_PAGE'
export const SERVICE_NEXT_PAGE = 'NEXT_PAGE'
export const SERVICE_PREPARE_JSON_ITEM = "ITEM_JSON"


export const DEVICE_GET_ALL = 'GET_ALL'
export const DEVICE_ADD_NEW = 'ADD_NEW_DEVICE'
export const DEVICE_SET_PAGINATION = 'SET_PAGINATION'
export const DEVICE_PREV_PAGE = 'PREV_PAGE'
export const DEVICE_NEXT_PAGE = 'NEXT_PAGE'
export const DEVICE_ADD_FILTER = 'ADD_FILTER'
export const DEVICE_REMOVE_FILTER = 'REMOVE_FILTER'

export const MODIFICATION_GET_ALL = 'GET_ALL'
export const MODIFICATION_GET_ONE_PAGE = 'GET_ONE_PAGE'
export const MODIFICATION_CREATE = 'CREATE'

export const CARRIER_GET_ALL = 'GET_ALL'
export const CARRIER_GET_ONE_PAGE = 'GET_ONE_PAGE'

export const DEVICE_TYPE_GET_ALL = 'GET_ALL'
export const DEVICE_TYPE_GET_ONE_PAGE = 'GET_ONE_PAGE'

export const COMPANY_GET_ALL = 'GET_ALL'

export const COMPANY_UPDATE = 'UPDATE'
export const COMPANY_SET_PAGINATION = 'SET_PAGINATION'
export const COMPANY_PREV_PAGE = 'PREV_PAGE'
export const COMPANY_NEXT_PAGE = 'NEXT_PAGE'
